name: deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: nix
    steps:
      - uses: actions/checkout@v3
      - run: nix run .#deploy
        env:
          SSH_HOMEPAGE_KEY: ${{ secrets.SSH_HOMEPAGE_KEY }}
